"""
Explainable Forensic Report Generator for FakeProbe-X.
Converts UnifiedForensicReport into clean markdown and structured forensic certificates.
"""

from .types import UnifiedForensicReport


class ForensicReportGenerator:
    """Renders human-readable and auditable forensic analysis reports."""

    @staticmethod
    def generate_markdown_report(report: UnifiedForensicReport) -> str:
        """Render complete markdown forensic certificate."""
        md = []
        md.append(f"# 🛡️ FakeProbe-X Forensic Analysis Report")
        md.append(f"**Sample**: `{report.sample_name}` | **Modality**: `{report.modality.upper()}`\n")

        md.append("## 1. Executive Forensic Verdict")
        verdict_icon = "🚨" if report.final_verdict.value == "FAKE" else ("✅" if report.final_verdict.value == "REAL" else "⚠️")
        md.append(f"### {verdict_icon} Verdict: **{report.final_verdict.value}**")
        md.append(f"- **Confidence**: `{report.confidence*100:.1f}%`")
        md.append(f"- **Forensic Reliability**: `{report.reliability_level.value}` (`{report.reliability:.2f}` / 1.00)")
        md.append(f"- **Uncertainty Score**: `{report.uncertainty_score:.2f}` (Threshold: < 0.60)")
        md.append(f"- **Fake Probability**: `{report.final_fake_probability*100:.2f}%` | **Real Probability**: `{report.final_real_probability*100:.2f}%`\n")

        md.append("## 2. Input Signal Quality Assessment")
        md.append(f"- **Overall Quality Level**: `{report.quality.quality_level.value}` (Score: `{report.quality.quality_score:.2f}`)")
        md.append(f"- **Acceptable for Forensics**: `{'YES' if report.quality.is_acceptable else 'NO'}`")
        if report.quality.issues:
            md.append("- **Quality Issues Identified**:")
            for issue in report.quality.issues:
                md.append(f"  - ⚠️ {issue}")
        else:
            md.append("- **Quality Issues**: None (High quality source media)")
        md.append("")

        md.append("## 3. Forensic Evidence Breakdown")
        md.append("| Evidence Source | Modality | Anomaly Score | Reliability | Effective Weight | Description |")
        md.append("|:---|:---|:---:|:---:|:---:|:---|")
        for ev in report.evidence_list:
            md.append(
                f"| **{ev.name}** | `{ev.modality}` | `{ev.score*100:.1f}%` | `{ev.reliability:.2f}` | `{ev.weight:.2f}` | {ev.description} |"
            )
        md.append("")

        md.append("## 4. Reasoning & Forensic Indicators")
        for reason in report.reasons:
            md.append(f"- {reason}")
        md.append("")

        md.append("## 5. Technical Traceability")
        for det in report.detector_results:
            md.append(f"- **Model**: `{det.model}`")
            md.append(f"  - Raw Decision Margin: `{det.raw_score:.4f}`")
            md.append(f"  - Model Prediction: `{det.prediction.value}` ({det.detail_label})")
            md.append(f"  - Fake Probability: `{det.probability_fake*100:.2f}%`")
        md.append("")

        md.append("---")
        md.append("*Generated by FakeProbe-X Reliability-Aware Multimodal Deepfake Forensics System.*")

        return "\n".join(md)
