import json
from .types import UnifiedForensicReport


class ForensicReportGenerator:
    """Renders human-readable and auditable forensic analysis reports."""

    @staticmethod
    def generate_json_report(report: UnifiedForensicReport) -> str:
        """Render complete structured JSON forensic audit data."""
        return json.dumps(report.to_dict(), indent=2)

    @staticmethod
    def generate_markdown_report(report: UnifiedForensicReport) -> str:
        """Render complete markdown forensic certificate."""
        md = []
        md.append(f"# 🛡️ FakeProbe-X Forensic Analysis Report")
        md.append(f"**Sample**: `{report.sample_name}` | **Modality**: `{report.modality.upper()}`\n")

        md.append("## 1. Executive Forensic Verdict")
        verdict_icon = "🚨" if report.final_verdict.value == "FAKE" else ("✅" if report.final_verdict.value == "REAL" else "⚠️")
        md.append(f"### {verdict_icon} Verdict: **{report.final_verdict.value}**")
        md.append(f"- **Confidence**: `{report.confidence*100:.1f}%`")
        md.append(f"- **Forensic Reliability**: `{report.reliability_level.value}` (`{report.reliability:.2f}` / 1.00)")
        md.append(f"- **Uncertainty Score**: `{report.uncertainty_score:.2f}` (Threshold: < 0.60)")
        md.append(f"- **Fake Probability**: `{report.final_fake_probability*100:.2f}%` | **Real Probability**: `{report.final_real_probability*100:.2f}%`")
        md.append(f"- **Summary**: {report.summary_text}\n")

        md.append("## 2. Input Signal Quality Assessment")
        md.append(f"- **Overall Quality Level**: `{report.quality.quality_level.value}` (Score: `{report.quality.quality_score:.2f}`)")
        md.append(f"- **Acceptable for Forensics**: `{'YES' if report.quality.is_acceptable else 'NO'}`")
        if report.quality.issues:
            md.append("- **Quality Issues Identified**:")
            for issue in report.quality.issues:
                md.append(f"  - ⚠️ {issue}")
        else:
            md.append("- **Quality Issues**: None (High quality source media)")
        
        if report.quality.metrics:
            md.append("- **Physical Metrics**:")
            for k, v in report.quality.metrics.items():
                val_str = f"{v:.2f}" if isinstance(v, float) else str(v)
                md.append(f"  - `{k}`: `{val_str}`")
        md.append("")

        md.append("## 3. Forensic Evidence Breakdown")
        md.append("| Evidence Source | Modality | Anomaly Score | Reliability | Effective Weight | Description |")
        md.append("|:---|:---|:---:|:---:|:---:|:---|")
        for ev in report.evidence_list:
            md.append(
                f"| **{ev.name}** | `{ev.modality}` | `{ev.score*100:.1f}%` | `{ev.reliability:.2f}` | `{ev.weight:.2f}` | {ev.description} |"
            )
        md.append("")

        md.append("## 4. Model Agreement & Consistency")
        agree_label = "HIGH" if report.agreement_score >= 0.80 else ("MEDIUM" if report.agreement_score >= 0.50 else "LOW")
        md.append(f"- **Agreement Level**: `{agree_label}` (Score: `{report.agreement_score:.2f}`)")
        for det in report.detector_results:
            md.append(f"- **{det.model}** ({det.modality.upper()}): `{det.prediction.value}` (Probability: `{det.probability_fake*100:.1f}%`)")
        md.append("")

        # Temporal analysis if video
        if report.modality == "video":
            md.append("## 5. Temporal Video Forensics")
            suspicious = report.visual_artifacts.get("suspicious_frames", [])
            timestamps = report.visual_artifacts.get("frame_timestamps", [])
            frame_probs = report.visual_artifacts.get("frame_fake_probabilities", [])
            md.append(f"- **Total Frames Sampled**: `{len(timestamps) if timestamps else 'N/A'}`")
            md.append(f"- **Suspicious Frames Identified**: `{len(suspicious)}`")
            if suspicious:
                md.append("- **Suspicious Intervals**:")
                for sf in suspicious:
                    md.append(f"  - Timestamp `{sf['timestamp_sec']}s` (Frame {sf['frame_index']}): Fake Prob `{sf['fake_probability']*100:.1f}%` ({sf['severity']})")
            else:
                md.append("- **Suspicious Intervals**: None detected")
            md.append("")

        md.append("## 6. Reasoning & Forensic Indicators")
        for reason in report.reasons:
            md.append(f"- {reason}")
        md.append("")

        md.append("## 7. Technical Traceability")
        for det in report.detector_results:
            md.append(f"- **Model**: `{det.model}`")
            md.append(f"  - Raw Decision Margin: `{det.raw_score:.4f}`")
            md.append(f"  - Model Prediction: `{det.prediction.value}` ({det.detail_label})")
            md.append(f"  - Fake Probability: `{det.probability_fake*100:.2f}%`")
            md.append(f"  - Reliability Score: `{det.reliability:.2f}`")
        md.append("")

        md.append("---")
        md.append("*Generated by FakeProbe-X Reliability-Aware Multimodal Deepfake Forensics System.*")

        return "\n".join(md)

