import { useState, useRef, useEffect, useMemo, useCallback } from 'react';
import './App.css';

// Bundled copies of demo_results/*.json (generated by `npm run sync-demo`): used only if the API is down.
const BUNDLED = Object.fromEntries(
  Object.entries(import.meta.glob('./demo/*.json', { eager: true }))
    .map(([p, m]) => [p.split('/').pop().replace('.json', ''), m.default]),
);

const API = import.meta.env.VITE_API_URL ?? (window.location.port === '8000' ? '' : 'http://127.0.0.1:8000');

const LABELS = {
  AI_GENERATED: ['⚠ AI-GENERATED', 'bad'],
  POSSIBLY_AI: ['❓ POSSIBLY AI', 'warn'],
  LIKELY_REAL: ['✅ LOOKS REAL', 'ok'],
  NOT_ENOUGH_INFO: ['➖ NOT ENOUGH INFO', 'warn'],
};
const DOT = { bad: '🔴', warn: '🟠', ok: '🟢' };
const COLOR = { bad: '#ff5d73', warn: '#ffb84d', ok: '#3ddc97' };
const DEMOS = [
  ['video', 'ai', '🎬 Demo: Video'],
  ['image', 'real', '🖼 Demo: Real photo'],
  ['image', 'ai', '🖼 Demo: AI photo'],
  ['audio', 'real', '🎧 Demo: Real voice'],
  ['audio', 'ai', '🎧 Demo: AI voice'],
];
const EXT = {
  image: ['png', 'jpg', 'jpeg'],
  audio: ['wav', 'mp3', 'flac', 'm4a'],
  video: ['mp4', 'avi', 'mov', 'mkv'],
};
const MAX_MB = { image: 25, audio: 50, video: 150 };

const extOf = (f) => (f.name.split('.').pop() || '').toLowerCase();
const kindOf = (f) => {
  const e = extOf(f);
  if (f.type.startsWith('image') || EXT.image.includes(e)) return 'image';
  if (f.type.startsWith('audio') || EXT.audio.includes(e)) return 'audio';
  if (f.type.startsWith('video') || EXT.video.includes(e)) return 'video';
  return null;
};
const areaColor = (p) => (p >= 60 ? '#ff5d73' : p >= 45 ? '#ffb84d' : '#ffd966');
const fmt = (n, d = 2) => (typeof n === 'number' ? n.toFixed(d) : '—');
const bundledKey = (type, variant) => (variant === 'real' && type !== 'video' ? `${type}_real` : type);

async function api(path, opts) {
  let r;
  try {
    r = await fetch(API + path, opts);
  } catch {
    const err = new Error('The API is not running or cannot be reached. Start it with: uvicorn api:app --port 8000');
    err.offline = true;
    throw err;
  }
  if (!r.ok) {
    let detail = null;
    try { detail = (await r.json()).detail; } catch { /* not json */ }
    let msg = (detail && detail.message) || (typeof detail === 'string' ? detail : `The server answered with an error (${r.status}).`);
    if (r.status === 413) msg = 'That file is too large for the server.';
    if (r.status === 400 && /extension/i.test(msg)) msg = 'That file type is not supported. Use an image (png, jpg), a video (mp4, avi, mov, mkv) or an audio file (wav, mp3, flac, m4a).';
    const err = new Error(msg);
    err.status = r.status;
    err.runDemo = r.status === 503;
    throw err;
  }
  return r.json();
}

function Badge({ r }) {
  if (!r) return null;
  if (r.sample_data) return <span className="badge sample">Sample result (cached demo)</span>;
  if (r.cached_real_run) return <span className="badge cached">Cached real run · not a live analysis</span>;
  return <span className="badge live">Live analysis · {r.engine}</span>;
}

export default function App() {
  const [engine, setEngine] = useState('demo');
  const [health, setHealth] = useState(null);
  const [file, setFile] = useState(null);
  const [fileUrl, setFileUrl] = useState(null);
  const [kind, setKind] = useState('video');
  const [result, setResult] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null); // {message, offerDemo}
  const [sel, setSel] = useState(0); // index into frame_regions
  const [showAll, setShowAll] = useState(false);
  const [highlight, setHighlight] = useState(null); // area number
  const [chat, setChat] = useState([]);
  const [chatBusy, setChatBusy] = useState(false);
  const [q, setQ] = useState('');
  const [audioBuf, setAudioBuf] = useState(null);
  const [imgReady, setImgReady] = useState(0);
  const canvasRef = useRef(null);
  const videoRef = useRef(null);
  const audioRef = useRef(null);
  const waveRef = useRef(null);
  const imgRef = useRef(null);
  const chatRef = useRef(null);
  const resultTop = useRef(null);

  const HELLO = { who: 'a', text: "Hi! I answer only from the result above. I call small tools (summary, frame, intervals, modalities, audit) and explain in plain words. Try a suggestion." };
  useEffect(() => { setChat([HELLO]); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight; }, [chat]);

  useEffect(() => {
    api('/api/v1/health').then(setHealth).catch(() => setHealth({ offline: true }));
  }, []);

  const showResult = (r, k) => {
    setKind(k || r.media_type || kind);
    setResult(r); setSel(0); setShowAll(false); setHighlight(null);
    setChat([HELLO]);
    setTimeout(() => resultTop.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 60);
  };

  const loadDemo = useCallback(async (type, variant = 'ai') => {
    setError(null); setBusy(true);
    try {
      let r;
      try { r = await api(`/api/v1/demo/${type}?variant=${variant}`); } catch (e) {
        if (!e.offline) throw e;
        r = BUNDLED[bundledKey(type, variant)]; // API down: bundled copy
        if (!r) throw e;
      }
      showResult(r, type);
    } catch (e) { setError({ message: e.message, offerDemo: false }); } finally { setBusy(false); }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const onFile = async (f) => {
    if (!f) return;
    const k = kindOf(f);
    if (!k) {
      setError({ message: `“${f.name}” is not a supported file type. Use an image (png, jpg), a video (mp4, avi, mov, mkv) or an audio file (wav, mp3, flac, m4a).`, offerDemo: false });
      return;
    }
    const mb = f.size / 1048576;
    if (mb > MAX_MB[k]) {
      setError({ message: `That ${k} is ${mb.toFixed(0)} MB. The limit for ${k} files is ${MAX_MB[k]} MB — please use a smaller one.`, offerDemo: false });
      return;
    }
    if (fileUrl) URL.revokeObjectURL(fileUrl);
    const url = URL.createObjectURL(f);
    setError(null);
    setFile(f); setKind(k); setFileUrl(url); setResult(null); setAudioBuf(null);
    imgRef.current = null;
    if (k === 'image') {
      const im = new Image();
      im.onload = () => { imgRef.current = im; setImgReady((v) => v + 1); };
      im.src = url;
    } else {
      try {
        const Ctx = window.AudioContext || window.webkitAudioContext;
        setAudioBuf(await new Ctx().decodeAudioData(await f.arrayBuffer()));
      } catch { setAudioBuf(null); }
    }
  };

  const clearFile = () => {
    if (fileUrl) URL.revokeObjectURL(fileUrl);
    setFile(null); setFileUrl(null); setAudioBuf(null); imgRef.current = null;
  };

  const run = async (eng = engine) => {
    if (!file) { loadDemo(kind === 'image' || kind === 'audio' ? kind : 'video', 'ai'); return; }
    setBusy(true); setError(null);
    try {
      const fd = new FormData(); fd.append('file', file);
      const r = await api(`/api/v1/analyze?engine=${eng}`, { method: 'POST', body: fd });
      showResult(r, kind);
    } catch (e) {
      if (e.offline) {
        const fb = BUNDLED[bundledKey(kind, 'ai')];
        setError({ message: e.message, offerDemo: !!fb });
      } else setError({ message: e.message, offerDemo: !!e.runDemo || eng !== 'demo' });
    } finally { setBusy(false); }
  };

  const regions = result?.frame_regions || [];
  const withBoxes = useMemo(() => regions.map((f, i) => ({ ...f, i })).filter((f) => f.regions.length), [regions]);
  const boxFrame = useMemo(() => regions.flatMap((fr, i) => fr.regions.map(() => i)), [regions]); // area n -> frame index
  const boxOffset = useMemo(() => { let n = 0; return regions.map((fr) => { const o = n; n += fr.regions.length; return o; }); }, [regions]);
  const totalBoxes = boxFrame.length;
  const fs = result?.frame_size;
  const isDemo = !!result?.demo;
  const usingUpload = !!file && !!result && !isDemo;
  const W = fs?.w || (usingUpload && imgRef.current?.naturalWidth) || 640;
  const H = fs?.h || (usingUpload && imgRef.current?.naturalHeight) || 360;

  // ---- Step 3 canvas
  const draw = useCallback(() => {
    const c = canvasRef.current;
    if (!c || !result) return;
    const x = c.getContext('2d');
    c.width = W; c.height = H;
    x.fillStyle = '#0a0e15'; x.fillRect(0, 0, W, H);
    let drawn = false;
    if (kind === 'image' && imgRef.current && usingUpload) { x.drawImage(imgRef.current, 0, 0, W, H); drawn = true; }
    const v = videoRef.current;
    if (kind === 'video' && usingUpload && v && v.videoWidth && v.readyState > 1) { x.drawImage(v, 0, 0, W, H); drawn = true; }
    const fsz = Math.max(12, W / 55);
    const pill = (text, px, py, right) => {
      x.font = `${fsz}px sans-serif`;
      const tw = x.measureText(text).width + 14;
      const bx = right ? W - tw - 6 : px;
      x.fillStyle = 'rgba(10,14,21,.85)'; x.fillRect(bx, py, tw, fsz + 10);
      x.fillStyle = '#e6ecf7'; x.fillText(text, bx + 7, py + fsz + 1);
    };
    const box = (r, col, label) => {
      x.strokeStyle = col; x.lineWidth = Math.max(2, W / 300); x.fillStyle = col + '2e';
      if (r.source === 'face_box') x.setLineDash([8, 5]);
      x.fillRect(r.x, r.y, r.w, r.h); x.strokeRect(r.x, r.y, r.w, r.h); x.setLineDash([]);
      x.font = `bold ${fsz}px sans-serif`;
      const tw = x.measureText(label).width + 10;
      const ty = r.y - fsz - 6 < 0 ? r.y + 2 : r.y - fsz - 6;
      const lx = Math.max(0, Math.min(r.x, W - tw));
      x.fillStyle = col; x.fillRect(lx, ty, tw, fsz + 6);
      x.fillStyle = '#000'; x.fillText(label, lx + 5, ty + fsz);
    };
    const pctOf = (r, fr) => Math.round((r.mean_anomaly ?? fr.score ?? 0) * 100);
    if (showAll) {
      regions.forEach((fr, fi) => fr.regions.forEach((r, ri) => box(r, areaColor(pctOf(r, fr)), `#${boxOffset[fi] + ri + 1}`)));
    } else if (regions[sel]) {
      const fr = regions[sel];
      fr.regions.forEach((r, i) => {
        const n = boxOffset[sel] + i + 1;
        box(r, areaColor(pctOf(r, fr)), r.source === 'face_box' ? `#${n} Face area (approx.)` : `#${n} · ${pctOf(r, fr)}%`);
      });
      if (fr.timestamp_sec != null) pill(`t = ${fr.timestamp_sec}s`, 0, 6, true);
    }
    if (!drawn) pill(usingUpload ? 'Frame loading…' : isDemo ? 'Illustration: cached example on a blank frame (not your file)' : 'Frame not available', 6, H - fsz - 16, false);
  }, [result, regions, sel, showAll, kind, usingUpload, isDemo, W, H, boxOffset]);

  useEffect(() => {
    if (!result || kind === 'audio') return undefined;
    const v = videoRef.current;
    const fr = regions[sel];
    if (kind === 'video' && usingUpload && v && !showAll && fr?.timestamp_sec != null && isFinite(v.duration)) {
      v.onseeked = draw; v.currentTime = fr.timestamp_sec;
    }
    draw();
    return () => { if (v) v.onseeked = null; };
  }, [draw, result, kind, sel, regions, usingUpload, showAll, imgReady]);

  // ---- waveform
  const segs = result?.audio_segments || [];
  const dur = (usingUpload && audioBuf?.duration) || result?.audio_duration_sec || result?.video_duration_sec || 20;
  useEffect(() => {
    const c = waveRef.current;
    if (!c || !result || kind === 'image') return;
    const x = c.getContext('2d'), w = c.width, h = c.height;
    x.clearRect(0, 0, w, h);
    segs.forEach((g, i) => { x.fillStyle = highlight === `a${i}` ? 'rgba(255,93,115,.55)' : 'rgba(255,93,115,.3)'; x.fillRect((g.start / dur) * w, 0, ((g.end - g.start) / dur) * w, h); });
    const d = audioBuf && usingUpload ? audioBuf.getChannelData(0) : null;
    x.fillStyle = '#4cc9f0';
    for (let i = 0; i < w; i += 2) {
      let a;
      if (d) {
        let m = 0; const st = Math.floor((i / w) * d.length), n = Math.max(1, Math.floor((d.length / w) * 2));
        for (let k = 0; k < n; k += Math.ceil(n / 20)) m = Math.max(m, Math.abs(d[st + k] || 0));
        a = m;
      } else a = 0.12 + 0.4 * Math.abs(Math.sin(i * 0.05) * Math.sin(i * 0.013 + 1));
      x.fillRect(i, h / 2 - a * h * 0.45, 1.5, a * h * 0.9);
    }
    x.fillStyle = '#fff'; x.font = '11px sans-serif';
    segs.forEach((g, n) => x.fillText(`#${n + 1}`, (g.start / dur) * w + 3, 12));
  }, [result, kind, segs, dur, audioBuf, usingUpload, highlight]);

  const seekAudio = (e) => {
    const c = waveRef.current; const t = (e.nativeEvent.offsetX / c.clientWidth) * dur;
    const i = segs.findIndex((g) => t >= g.start && t <= g.end);
    setHighlight(i >= 0 ? `a${i}` : null);
    const a = audioRef.current;
    if (a && a.src && usingUpload) { a.currentTime = t; a.play().catch(() => {}); }
  };

  const jumpTo = (a) => {
    setHighlight(a.n); setShowAll(false);
    const idx = boxFrame[a.n - 1];
    if (idx != null) setSel(idx);
    canvasRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };

  // ---- chat
  const ask = async (text) => {
    if (!text.trim() || chatBusy) return;
    setQ('');
    setChat((c) => [...c, { who: 'u', text }]);
    if (!result) { setChat((c) => [...c, { who: 'a', text: 'Run a check or a demo first, so I have a result to read.' }]); return; }
    setChatBusy(true);
    try {
      const r = await api('/api/v1/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: text, result }) });
      setChat((c) => [...c, { who: 'a', text: r.answer, tools: r.tools_used, llm: r.llm_used }]);
    } catch {
      setChat((c) => [...c, { who: 'a', text: 'The chat service is offline (start the API with uvicorn api:app --port 8000). The result and evidence above are still valid.' }]);
    } finally { setChatBusy(false); }
  };

  const chips = useMemo(() => {
    if (!result) return ['Summarise the verdict', 'How reliable is this?'];
    const c = ['Summarise the verdict'];
    const tl = result.timeline || [];
    if (result.media_type === 'video' && tl.length) {
      const p = tl.reduce((a, b) => (b.fake_prob > a.fake_prob ? b : a));
      c.push(`Why is the strongest moment at ${p.t}s?`, 'When are the suspicious moments?', 'Do the voice and lip-sync agree?');
    } else if (result.media_type === 'audio') c.push('When are the suspicious segments?');
    else c.push('Where are the suspicious areas?');
    c.push('How reliable is this?');
    if (result.verdict_label === 'POSSIBLY_AI') c.push('Why is this UNCERTAIN?');
    return c;
  }, [result]);

  const [label, sev] = result ? LABELS[result.verdict_label] || LABELS.NOT_ENOUGH_INFO : [];
  const areas = result?.all_detected_areas || [];
  const kindWord = { video: 'video', image: 'image', audio: 'audio clip' }[result?.media_type || kind];
  const ready = { fast: health?.fast_ready, deep: health?.deep_ready };
  const demoWithFile = engine === 'demo' && !!file;

  return (
    <>
      <header>
        <h1>🔍 DeepTrace — Deepfake Forensics</h1>
        <span className="tag">Upload → Check → See where → Ask why</span>
        {health && (
          <span className="tag" title={health.fast_reason || health.deep_reason || ''}>
            {health.offline ? 'API offline · bundled demo only' : `demo ✔ · fast ${health.fast_ready ? '✔' : '✖'} · deep ${health.deep_ready ? '✔' : '✖'}`}
          </span>
        )}
      </header>
      <main>
        {/* STEP 1 */}
        <section className="card">
          <h2>Step 1 · Upload a video, image or audio</h2>
          <p className="mu">Choose a file and press the button. The AI will tell you if it looks real or fake.</p>
          {fileUrl && kind === 'video' && <video ref={videoRef} src={fileUrl} controls playsInline />}
          {fileUrl && kind === 'image' && <img className="preview" src={fileUrl} alt="Your uploaded file" />}
          {fileUrl && kind === 'audio' && <audio ref={audioRef} src={fileUrl} controls style={{ width: '100%' }} />}
          <div className="row">
            <label className="drop" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); onFile(e.dataTransfer.files[0]); }}>
              {file ? `📎 ${file.name}` : 'Drag & drop a file here, or click to choose'}
              <input type="file" accept="video/*,image/*,audio/*,.mkv,.m4a,.flac" hidden onChange={(e) => { onFile(e.target.files[0]); e.target.value = ''; }} />
            </label>
            {file && <button className="g" onClick={clearFile}>Remove file</button>}
          </div>
          <div className="row">
            <span className="mu">Engine:</span>
            {[['demo', 'Demo (cached)'], ['fast', 'Fast (live)'], ['deep', 'Deep (slow)']].map(([k, t]) => (
              <button key={k} className={'g' + (engine === k ? ' on' : '')} onClick={() => setEngine(k)}>{t}</button>
            ))}
            <button className="run" disabled={busy} onClick={() => run()}>{busy ? 'Checking…' : '🔍 Check if it is AI'}</button>
          </div>
          {demoWithFile && (
            <div className="notice" role="status">
              <b>Demo mode shows a cached example, not your file.</b> Your file stays visible here, but it is not analysed.
              <div className="row">
                <span className="small">Analyse it for real with:</span>
                {['fast', 'deep'].map((k) => (
                  <button key={k} className="g" disabled={health && !ready[k]} onClick={() => { setEngine(k); run(k); }}
                    title={health && !ready[k] ? (k === 'fast' ? health.fast_reason : health.deep_reason) || 'not ready' : ''}>
                    {k === 'fast' ? 'Fast engine' : 'Deep engine'}{health && !ready[k] ? ' (not ready)' : ''}
                  </button>
                ))}
              </div>
              {health && !health.offline && !ready.fast && !ready.deep && (
                <div className="small mu">No live engine is installed on this machine ({health.fast_reason}). Demo mode is the only option here.</div>
              )}
            </div>
          )}
          <div className="row">
            <span className="mu">Try a demo:</span>
            {DEMOS.map(([t, v, text]) => (
              <button key={text} className="g" disabled={busy} onClick={() => { clearFile(); loadDemo(t, v); }}>{text}</button>
            ))}
          </div>
          {busy && (
            <div className="busy" role="status"><span className="spinner" aria-hidden="true" />
              {engine === 'deep' && file ? 'Analysing… this can take 1–2 minutes on Deep (CPU).'
                : engine === 'fast' && file ? 'Analysing… this can take up to a minute.' : 'Loading…'}
            </div>
          )}
          {error && (
            <div className="err" role="alert"><span>⚠ {error.message}</span>
              {error.offerDemo && <button className="run" onClick={() => { setEngine('demo'); setError(null); if (file) run('demo'); else loadDemo(kind, 'ai'); }}>Run demo instead</button>}
            </div>
          )}
        </section>

        <div ref={resultTop} />
        {result && (
          <>
            {/* STEP 2 */}
            <section className="card">
              <h2>Step 2 · Result</h2>
              <Badge r={result} />
              {isDemo && file && <p className="small" style={{ color: 'var(--warn)' }}>This is a cached example for a {kind}; it is not the result for “{file.name}”.</p>}
              <div className="verdict">
                <div className="big" style={{ color: COLOR[sev] }}>{label}</div>
                <div>
                  <div className="pct">{result.ai_probability_pct != null ? `${result.ai_probability_pct}%` : '—'}</div>
                  <div className="mu small">AI-probability estimate for this {kindWord} · certainty: <b>{result.certainty}</b></div>
                </div>
              </div>
              {result.provenance && <div className="mu small">{result.provenance}</div>}
              <b>Why we say this:</b>
              {(result.reasons || []).map((r, i) => <div className="reason" key={i}>{DOT[r.severity]} {r.text}</div>)}
              {!(result.reasons || []).length && <div className="mu small">No reasons were returned.</div>}
            </section>

            {/* STEP 3 */}
            <section className="card">
              <h2>Step 3 · Where is it fake?</h2>
              {kind !== 'audio' && result.media_type !== 'audio' && (
                regions.length === 0 ? <p className="mu">This result contains no position data, so no boxes are drawn.</p> : (
                  <>
                    {totalBoxes === 0 && <p className="mu">No suspicious areas were found, so no boxes are drawn.</p>}
                    {fs?.estimated && <p className="mu small">Frame size is estimated from the box positions, so placement is approximate.</p>}
                    {isDemo && file && <p className="mu small">Your file is shown in Step 1. The boxes below belong to the cached example, so they are not drawn on your file.</p>}
                    <div className="row">
                      {result.media_type === 'video' && withBoxes.map((f) => (
                        <button key={f.i} className={'g' + (!showAll && sel === f.i ? ' on' : '')} onClick={() => { setShowAll(false); setSel(f.i); }}>{f.timestamp_sec}s</button>
                      ))}
                      {totalBoxes > 0 && <button className={'g' + (showAll ? ' on' : '')} onClick={() => setShowAll(true)}>Show ALL on one image</button>}
                    </div>
                    <canvas ref={canvasRef} className="ev" />
                    {!showAll && regions[sel] && (
                      <div className="mu small">
                        {regions[sel].timestamp_sec != null && <b>t={regions[sel].timestamp_sec}s · </b>}score {fmt(regions[sel].score)} · {regions[sel].regions.length} box(es)
                        {regions[sel].regions.some((r) => r.source === 'face_box') && ' · approximate (face area)'}
                      </div>
                    )}
                    {showAll && <div className="mu small">All detected areas from every checked moment; numbers match the list below. Overlapping boxes = the same spot flagged repeatedly.</div>}
                  </>
                )
              )}
              {result.media_type === 'video' && (result.timeline || []).length > 0 && (
                <Timeline tl={result.timeline} regions={regions} sel={sel} showAll={showAll} line={result.engine !== 'fast'}
                  onPick={(i) => { setShowAll(false); setSel(i); }} />
              )}
              {result.media_type !== 'image' && (
                <div className="sub">
                  <b>🎧 Voice evidence</b>
                  {usingUpload && kind === 'audio' && <div className="small mu">Your clip is in the player in Step 1.</div>}
                  {segs.length === 0 ? (
                    <p className="mu small">{result.media_type === 'audio' ? 'The voice checker gives one score for the whole clip, so it cannot say which seconds are fake. ' : 'No voice time segments are available for this result. '}The whole-clip result is in “Why we say this”.</p>
                  ) : (
                    <>
                      {result.sample_data && <div className="mu small">Segment times in this demo are sample data.</div>}
                      <canvas ref={waveRef} width="640" height="110" className="wave" onClick={seekAudio} />
                      <div className="mu small">Red blocks = parts the AI believes are synthetic. Click the wave to play from there{usingUpload ? '' : ' (the wave shape is an illustration)'}.</div>
                      {segs.map((g, i) => (
                        <div key={i} className={'area' + (highlight === `a${i}` ? ' hl' : '')} onClick={() => { setHighlight(`a${i}`); const a = audioRef.current; if (a && a.src && usingUpload) { a.currentTime = g.start; a.play().catch(() => {}); } }}>
                          <span className="num" style={{ background: '#ff5d73' }}>{i + 1}</span><b>{g.start}s – {g.end}s</b>: {g.reason} — <span style={{ color: '#ff5d73' }}>{Math.round(g.score * 100)}% synthetic</span>
                        </div>
                      ))}
                    </>
                  )}
                </div>
              )}
              {result.media_type !== 'audio' && (
                <div className="sub">
                  <b>Every place the AI found</b>
                  {areas.length === 0 ? <p className="mu small">Nothing to list: this result has no detected areas.</p> : (
                    <>
                      <div style={{ margin: '6px 0' }}>{areas.length} area(s) found. Click one to jump to it.</div>
                      {areas.map((a) => (
                        <div key={a.n} className={'area' + (highlight === a.n ? ' hl' : '')} onClick={() => jumpTo(a)}>
                          <span className="num" style={{ background: areaColor(a.percent_fake) }}>{a.n}</span>
                          {a.time !== '-' ? <>At <b>{a.time}</b> · </> : null}
                          <b>{a.where}</b> — {a.what}. <span style={{ color: areaColor(a.percent_fake) }}>{a.label} ({a.percent_fake}%)</span>
                        </div>
                      ))}
                    </>
                  )}
                </div>
              )}
            </section>
          </>
        )}

        {/* STEP 4 */}
        <section className="card">
          <h2>Step 4 · 🤖 Ask the AI assistant</h2>
          <div className="chat" ref={chatRef}>
            {chat.map((m, i) => (
              <div key={i} className={'m ' + m.who}>
                {m.tools && <div className="tool">🔧 {m.tools.map((t) => t + '()').join(' → ')}{m.llm ? ' · LLM reworded' : ' · rule-based'}</div>}
                {m.text}
              </div>
            ))}
          </div>
          <div className="row">{chips.map((c) => <button key={c} className="chip" onClick={() => ask(c)}>{c}</button>)}</div>
          <div className="row">
            <input type="text" value={q} placeholder="Ask about the evidence…" onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && ask(q)} />
            <button disabled={chatBusy} onClick={() => ask(q)}>Ask</button>
          </div>
        </section>

        {result && (
          <details className="card">
            <summary>⚙ Technical details (for experts)</summary>
            <div className="tech">
              <h3>Scores</h3>
              <Bars result={result} />
              {result.reliability_level && <p className="mu small">Reliability: {result.reliability_level} · confidence {fmt(result.confidence)}</p>}
              <h3>Timings</h3>
              <pre>{JSON.stringify(result.processing || 'not recorded', null, 1)}</pre>
              {result.sync_evidence?.offset_frames != null && <><h3>Lip-sync</h3><pre>{JSON.stringify(result.sync_evidence, null, 1)}</pre></>}
              {(result.evidence_list || result.evidence) && <><h3>Evidence</h3><pre>{JSON.stringify(result.evidence_list || result.evidence, null, 1)}</pre></>}
              {(result.suspicious_timeline || []).length > 0 && (
                <>
                  <h3>Suspicious intervals</h3>
                  <div className="scroll"><table>
                    <thead><tr><th>#</th><th>start</th><th>end</th><th>peak</th></tr></thead>
                    <tbody>{result.suspicious_timeline.map((t, i) => <tr key={i}><td>{i + 1}</td><td>{t.start_time}s</td><td>{t.end_time}s</td><td>{fmt(t.peak_score, 3)}</td></tr>)}</tbody>
                  </table></div>
                </>
              )}
              {regions.length > 0 && (
                <>
                  <h3>Boxes (selected moment)</h3>
                  <div className="scroll"><table>
                    <thead><tr><th>x,y</th><th>w×h</th><th>mean</th><th>max</th><th>reliab.</th><th>source</th></tr></thead>
                    <tbody>{(regions[sel]?.regions || []).map((r, i) => (
                      <tr key={i}><td>{r.x},{r.y}</td><td>{r.w}×{r.h}</td><td>{fmt(r.mean_anomaly)}</td><td>{fmt(r.max_anomaly)}</td><td>{fmt(r.reliability)}</td><td>{r.source}</td></tr>
                    ))}</tbody>
                  </table></div>
                </>
              )}
              {result.visual_evidence?.anomaly_map_path && <img className="heat" alt="anomaly heatmap" src={API + result.visual_evidence.anomaly_map_path} />}
              <h3>Raw JSON</h3>
              <pre className="raw">{JSON.stringify(result, null, 1)}</pre>
            </div>
          </details>
        )}
      </main>
      <footer>Estimate from pretrained models — not legal proof.</footer>
    </>
  );
}

function Bars({ result }) {
  const m = result.modalities || {};
  const rows = [['Visual', m.visual_score], ['Audio', m.audio_score], ['Lip-sync mismatch', m.sync_desync_score], ['Overall', result.manipulation_score ?? result.final_fake_probability]]
    .filter(([, v]) => typeof v === 'number');
  if (!rows.length) return <p className="mu small">No raw scores in this result.</p>;
  return rows.map(([k, v]) => (
    <div className="mod" key={k}><span>{k}</span><div className="bar"><i style={{ width: `${Math.round(v * 100)}%`, background: v > 0.5 ? '#ff5d73' : v > 0.35 ? '#ffb84d' : '#3ddc97' }} /></div><span>{fmt(v)}</span></div>
  ));
}

function Timeline({ tl, regions, onPick, sel, showAll, line }) {
  const w = 640, h = 160, p = 24;
  const tmax = Math.max(...tl.map((d) => d.t), 1);
  const X = (t) => p + (t / tmax) * (w - 2 * p), Y = (v) => h - p - v * (h - 2 * p);
  const pick = (t) => { const i = regions.findIndex((f) => f.timestamp_sec === t); if (i >= 0) onPick(i); };
  const pts = [...tl].sort((a, b) => a.t - b.t);
  return (
    <div className="sub">
      <b>Score over time</b>
      <svg viewBox={`0 0 ${w} ${h}`} width="100%" role="img" aria-label="Fake probability at each checked moment">
        {line && <><line x1={p} x2={w - p} y1={Y(0.5)} y2={Y(0.5)} stroke="#ffb84d" strokeDasharray="4 4" /><text x={w - p - 60} y={Y(0.5) - 4}>0.5 line</text></>}
        <polyline fill="none" stroke="#4cc9f0" strokeWidth="2" points={pts.map((d) => `${X(d.t)},${Y(d.fake_prob)}`).join(' ')} />
        {tl.map((d, i) => (
          <circle key={i} cx={X(d.t)} cy={Y(d.fake_prob)} r={!showAll && regions[sel]?.timestamp_sec === d.t ? 7 : 4.5} fill={d.suspicious ? '#ff5d73' : '#4cc9f0'} style={{ cursor: 'pointer' }} onClick={() => pick(d.t)}>
            <title>{`${d.t}s · ${fmt(d.fake_prob)}`}</title>
          </circle>
        ))}
        <text x={p} y={h - 6}>0s</text><text x={w - p - 20} y={h - 6}>{tmax}s</text>
      </svg>
      <div className="mu small">Each dot is one checked moment (not every frame). Red dot = suspicious. Click a dot to see its boxes.</div>
    </div>
  );
}
